"""Move a generated MOV/MP4 index through its owned inode, without reopening paths."""

from __future__ import annotations

import os
import struct

from .errors import MCPVideoError
from .limits import FASTSTART_COPY_CHUNK_BYTES, MAX_FASTSTART_MOOV_BYTES

_CONTAINERS = {b"moov", b"trak", b"mdia", b"minf", b"stbl"}


def _invalid() -> MCPVideoError:
    return MCPVideoError("Staged MP4 index cannot be relocated safely", code="invalid_faststart_output")


def _read(descriptor: int, size: int, offset: int) -> bytes:
    data = bytearray()
    while len(data) < size:
        chunk = os.pread(descriptor, size - len(data), offset + len(data))
        if not chunk:
            raise _invalid()
        data.extend(chunk)
    return bytes(data)


def _write(descriptor: int, data: bytes, offset: int) -> None:
    written = 0
    while written < len(data):
        count = os.pwrite(descriptor, data[written:], offset + written)
        if count <= 0:
            raise _invalid()
        written += count


def _header(data: bytes, position: int, end: int) -> tuple[int, bytes, int]:
    if end - position < 8:
        raise _invalid()
    size, kind = struct.unpack_from(">I4s", data, position)
    header = 8
    if size == 1:
        if end - position < 16:
            raise _invalid()
        size = struct.unpack_from(">Q", data, position + 8)[0]
        header = 16
    elif size == 0:
        size = end - position
    if size < header or size > end - position:
        raise _invalid()
    return size, kind, header


def _table(kind: bytes, payload: bytes, delta: int, insertion: int, moov_start: int) -> tuple[bytes, bytes]:
    if len(payload) < 8:
        raise _invalid()
    count = struct.unpack_from(">I", payload, 4)[0]
    width = 4 if kind == b"stco" else 8
    if len(payload) != 8 + count * width:
        raise _invalid()
    code = ">I" if width == 4 else ">Q"
    promoted = kind == b"stco" and any(
        struct.unpack_from(code, payload, 8 + index * width)[0] + delta >= 1 << 32 for index in range(count)
    )
    output_width = 8 if promoted else width
    if 8 + count * output_width > MAX_FASTSTART_MOOV_BYTES:
        raise _invalid()
    output = bytearray(8 + count * output_width)
    output[:8] = payload[:8]
    output_code = ">Q" if output_width == 8 else ">I"
    for index in range(count):
        value = struct.unpack_from(code, payload, 8 + index * width)[0]
        if not insertion <= value < moov_start:
            raise _invalid()
        value += delta
        if value >= 1 << 64:
            raise _invalid()
        struct.pack_into(output_code, output, 8 + index * output_width, value)
    return b"co64" if promoted else kind, bytes(output)


def _rebuild(data: bytes, delta: int, insertion: int, moov_start: int, depth: int = 0) -> bytes:
    if depth > 5:
        raise _invalid()
    position, output = 0, bytearray()
    while position < len(data):
        size, kind, header = _header(data, position, len(data))
        payload = data[position + header : position + size]
        if kind in _CONTAINERS:
            payload = _rebuild(payload, delta, insertion, moov_start, depth + 1)
        elif kind in {b"stco", b"co64"}:
            kind, payload = _table(kind, payload, delta, insertion, moov_start)
        elif kind == b"cmov":
            raise _invalid()  # Compressed legacy indexes are not generated by our muxer.
        box_size = header + len(payload)
        output.extend(struct.pack(">I4sQ", 1, kind, box_size) if header == 16 else struct.pack(">I4s", box_size, kind))
        output.extend(payload)
        if len(output) > MAX_FASTSTART_MOOV_BYTES:
            raise _invalid()
        position += size
    return bytes(output)


def _layout(descriptor: int) -> tuple[int, int, int] | None:
    length, position, insertion, moov = os.fstat(descriptor).st_size, 0, None, None
    while position < length:
        header = _read(descriptor, min(16, length - position), position)
        # Parse against the full remaining file without allocating its media.
        size, kind = struct.unpack_from(">I4s", header) if len(header) >= 8 else (0, b"")
        if size == 1:
            if len(header) < 16:
                raise _invalid()
            size = struct.unpack_from(">Q", header, 8)[0]
            minimum = 16
        else:
            minimum = 8
            size = size or length - position
        if size < minimum or size > length - position:
            raise _invalid()
        if kind == b"mdat" and insertion is None:
            insertion = position
        if kind == b"moov":
            if moov is not None:
                raise _invalid()
            moov = (position, size)
        if kind == b"moof":
            return None  # Fragmented outputs already have an early initialization index.
        position += size
    if moov is None or insertion is None:
        raise _invalid()
    start, size = moov
    if start < insertion:
        return None
    if start + size != length or size > MAX_FASTSTART_MOOV_BYTES:
        raise _invalid()
    return insertion, start, size


def relocate_index(descriptor: int) -> None:
    """Retain encoded packets and early-index semantics on Darwin descriptor outputs."""
    try:
        layout = _layout(descriptor)
        if layout is None:
            return
        insertion, start, old_size = layout
        original = _read(descriptor, old_size, start)
        delta = old_size
        while True:
            index = _rebuild(original, delta, insertion, start)
            if len(index) == delta:
                break
            if len(index) < delta or len(index) > MAX_FASTSTART_MOOV_BYTES:
                raise _invalid()
            delta = len(index)  # stco promotion can grow the index; offsets use the final size.
        position = start
        while position > insertion:
            count = min(FASTSTART_COPY_CHUNK_BYTES, position - insertion)
            position -= count
            _write(descriptor, _read(descriptor, count, position), position + delta)
        _write(descriptor, index, insertion)
        os.ftruncate(descriptor, start + delta)
    except OSError as exc:
        raise _invalid() from exc
